### PR TITLE
Show .less file and line reference for thrown exception

### PR DESCRIPTION
**Pull request by timint**

### CODE REVIEW

**Comment by Krinkle** [comment]
@timint Could you provide an example of invalid input where this works as intended?

I tried various inputs, but in all these cases I found `$a->index` and `currentFileInfo` to both be undefined, thus causing PHP errors. Assuming this does work in some cases, it would likely need to be accessed conditionally.

```less
@val: null;
.mymixin {
    myprop: @val * 42 - "x";
}
```
```less
.mymixin(@val) {
    myprop: @val * calc(red - green);
}

b {
    .mymixin(null);
}
```

`$ bin/lessc sample.less`
> PHP Notice:  Undefined property: Less_Tree_Keyword::$index in …less.php/lib/Less/Tree/Operation.php on line 44
> PHP Notice: Undefined property: Less_Tree_Keyword::$currentFileInfo in …less.php/lib/Less/Tree/Operation.php on line 44
> Uncaught Less_Exception_Compiler: Operation on an invalid type in tmp.less in …less.php/lib/Less/Tree/Mixin/Call.php:125

**Review by Krinkle — CHANGES_REQUESTED** [review]
Currently causes `Undefined property: Less_Tree_Keyword::$currentFileInfo`.

**Comment by timint** [comment]
I can't remember, I should have provided an example when I did this fresh, sorry.
All I can say is my commit solved my problem after spending hours trying to find which .less file and line was causing the error.

**Comment by Krinkle** [comment]
Aye, I understand. I'll close this for now but feel free to submit again in the future with an example.

**Pull request closed without merging**
