### PR TITLE
Support imports of remote resources

### LINKED ISSUE #27: Compiler doesn't import some remote CSS files
### Steps to reproduce (*)
1. On a .less file, import the following URL: @import url("https://fonts.googleapis.com/icon?family=Material+Icons");
2. Compile LESS

### Expected result (*)
* Font is imported correctly

### Actual result (*)
* We get this error: `File https://fonts.googleapis.com/icon not found `

### Root cause
We originally found this issue in Magento 2: https://github.com/magento/magento2/issues/25119

We were able to track down the issue down to the less.php library. This URL doesn't work because it doesn't have the "css" word in it, which the library takes into account when importing css files: https://github.com/wikimedia/less.php/blob/master/lib/Less/Tree/Import.php#L44

### PR DESCRIPTION
**Pull request by MaxSem**
Fixes #27

### CODE REVIEW

**Comment by Krinkle** [comment]
LGTM, but would recommend to have a runtime option for this. `Less_Parser` has an array of default options where this could fit well. Something like `'import_remote_url' => false` or some such.

**Comment by jedi-pl** [comment]
This PR should be merged as it saves the day

**Comment by barryvdh** [comment]
Note that Magento suggest using protocol-relative URLs: https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/css-topics/css-preprocess.html
`@import url('//fonts.googleapis.com/css?family=Titillium+Web:400,300,200,600.css');`

So `@import url("//fonts.googleapis.com/icon?family=Material+Icons");` would still fail with this PR, right?

**Comment by barryvdh** [comment]
FYI, this also fails with the new Fonts API: https://developers.google.com/fonts/docs/css2

@jdforrester Could you please consider this PR? It's breaking for Magento2 also.

**Review by Krinkle — CHANGES_REQUESTED** [review]
This should be behind an option to allow it to be disabled as defense in-depth (despite overall trust domain not mattering for this library given we only support trusted input only). Overall, it is welcome however.

**Comment by mrtuvn** [comment]
@MaxSem can you update change for resolve conflict file

**Pull request closed without merging**
