### PR TITLE
Tree_Url fetching patch

### PR DESCRIPTION
**Pull request by ciroarcadio**
## Resolves the lack of 'Url' node type while fetching the asset variables.

Fixed Issue:
======
When you try to extract variables via the getVariables() method, the parser throws a *"type missing in switch/case getVariableValue for Url"* exception if your asset contains a variable of type Url.

### CODE REVIEW

**Comment by Krinkle** [comment]
Hi @ciroarcadio, thanks for sharing the patch.

I didn't quite understand the exact issue you can into. Could you share a simple reproduction case for the issue, or better yet, add a unit test that fails without this patch?

**Comment by ciroarcadio** [comment]
> Hi @ciroarcadio, thanks for sharing the patch.
> 
> I didn't quite understand the exact issue you can into. Could you share a simple reproduction case for the issue, or better yet, add a unit test that fails without this patch?

Hi @Krinkle, here's a simple unit test.

```php
<?php

class phpunit_ParseVariablesTest extends phpunit_bootstrap {

	/**
	 * Test
	 */
	public function testVars() {
		echo "\nBegin Tests";

		$less_file			= "@test_url: url('just/a/test.jpg');";

		$parser = new Less_Parser();
		$parser->parse($less_file);
		$parser->getCss();

		$variables = $parser->getVariables();
		$this->assertArrayHasKey('@test_url', $variables);
	}

}
```
FYI: I originally wrote this patch for v1.8 (cause I needed it in a [magento 2 project](https://github.com/dnafactory/magento2-module-scss)), but the issue persists on the master branch, so that's why I suggested it.

**Comment by Krinkle** [comment]
@ciroarcadio I've added the following test locally with a stricted assertion and curious what kind of value would best suite your use case:

```php
<?php

class phpunit_ParserTest extends phpunit_bootstrap {
	public function testGetVariables() {
		$lessCode = '
			// Rule > Quoted
			@some_string: "foo";

			// Rule > Dimension
			@some_number: 123;

			// Rule > Dimension
			@some_unit: 12px;

			// Rule > Dimension
			@some_unit_op: 2px + 3px;

			// Rule > Color
			@some_color: #f9f9f9;

			// Rule > Url > Quoted
			@some_url: url("just/a/test.jpg");
		';

		$parser = new Less_Parser();
		$parser->parse( $lessCode );
		$css = $parser->getCss();

		$this->assertEquals( [], $parser->getVariables() );
	}
}
```
```diff
 Array (
+    '@some_string' => '"foo"'
+    '@some_number' => 123.0
+    '@some_unit' => '12px'
+    '@some_unit_op' => '5px'
+    '@some_color' => '#f9f9f9'
+    '@some_url' => '"just/a/test.jpg"'
 )
```

By roundtripping the `Quoted` node of the `Url` node only, the `url()` nature of it gets lost.

**Comment by Krinkle** [comment]
It looks like all the other cases basically duplicate the `genCSS()` method logic, so I'll keep that here as well, and thus reconstruct the `url()` syntax around it.

**Pull request closed without merging**
