### PR TITLE
Fix deprecation notices with PHP 8.2

### PR DESCRIPTION
**Pull request by glo71317**

### CODE REVIEW

**Comment by glo71317** [comment]
@sebastic I have added this PR -https://github.com/wikimedia/less.php/pull/86 changes in my PR because i got some more deprecation so i fixed and raised the PR.

**Comment by sebastic** [comment]
Just for the record, my PR only fixes the issues encountered by its use in icingaweb2.

**Comment by glo71317** [comment]
> Just for the record, my PR only fixes the issues encountered by its use in icingaweb2.

@sebastic You changes are there along with my changes so it will be good to merge this :) By merging this my issues also be fixed along with yours issues.

**Comment by glo71317** [comment]
@oyejorge Can you please review our PR and merge for proceeding because some depreciation and notices are throwing php8.2?

**Comment by oyejorge** [comment]
@glo71317 
> Can you please review our PR and merge

I'm not a maintainer of this package. Wikimedia took it over years ago

**Comment by glo71317** [comment]
> @glo71317
> 
> > Can you please review our PR and merge
> 
> I'm not a maintainer of this package. Wikimedia took it over years ago

So you know who is maintaining this library now so we can check with them, it seems, library is not updating frequently.

**Comment by glo71317** [comment]
@jdforrester Can you please review our PR and merge for proceeding because some depreciation and notices are throwing in php8.2?

**Comment by faizan-shk** [comment]
@AaronSchulz can you please look into this PR on prio. PHP8.2 is already released and we need these fixes ASAP

**Comment by sidolov** [comment]
Hi @Krinkle! Could you please review and merge this pull request? Thanks!

**Comment by glo71317** [comment]
@Krinkle do you have any plan to add php8.2 support

**Comment by Krinkle** [comment]
@glo71317 The release from last year (Less.php 3.1) introduced PHP 8 support. To my knowledge, there are no breaking change in PHP 8.2 that would make Less.php break or behave any difference. As such, this should already be ready for use in production with PHP 8.2. If you know of any bugs or changes that affect you, do let us know!

I've added PHP 8.2 in the CI matrix to confirm that all unit tests pass. In addition, I've also landed your PR and two other ones that address deprecation warnings (new in PHP 8.1 and 8.2) to ensure support on PHP 9.0 in the future (where these warnings might turn into errors).

**Comment by glo71317** [comment]
> @glo71317 The release from last year (Less.php 3.1) introduced PHP 8 support. To my knowledge, there are no breaking change in PHP 8.2 that would make Less.php break or behave any difference. As such, this should already be ready for use in production with PHP 8.2. If you know of any bugs or changes that affect you, do let us know!
> 
> I've added PHP 8.2 in the CI matrix to confirm that all unit tests pass. In addition, I've also landed your PR and two other ones that address deprecation warnings (new in PHP 8.1 and 8.2) to ensure support on PHP 9.0 in the future (where these warnings might turn into errors).

Thanks @Krinkle for the update!
As you merged yesterday some changes - https://github.com/wikimedia/less.php/commit/a93b0827b650a347f7c694e1e234f8c86efa8812,Can you please create a tag   along with these changes and also how it will be available as package. Please suggest.

**Pull request closed without merging**
