### PR TITLE
Tag v2.0.0

### PR DESCRIPTION
**Pull request by jdforrester**

### CODE REVIEW

**Comment by jdforrester** [comment]
(Note for @franzliedke.)

**Comment by Krinkle** [comment]
Seems to conflict with master where an 1.8.3 section was added.

**Comment by Krinkle** [comment]
I see. So you want to (or have already) undo the breaking change in PHP support on 1.8.x as 1.8.4, and re-release the breaking change as 2.x.

That sounds good to me, but from what I can see, that's not currently reflected in this commit.

The effective breaking change is that we raised the PHP requirement from 5.3+ to PHP 7.1+, right?

**Comment by jdforrester** [comment]
> I see. So you want to (or have already) undo the breaking change in PHP support on 1.8.x as 1.8.4, and re-release the breaking change as 2.x.

No. The breaking change (dropped PHP 5 support, dropping HHVM, dropping PHP 7.0, dropping PHP 7.1) shipped in 1.8.2, which it shouldn't have (my fault). This is making a new release which reflects the breaking change, plus per request of non-Wikimedia users temporarily re-adding PHP 7.1 support. As soon as this ships, we'll re-break PHP 7.1 support and release that as 3.0.0 I suppose.

See the discussion on #17 and #24.

**Comment by Krinkle** [comment]
I see. That could work, yeah. But given this 2.0.0 is the same as 1.8.4 and we've already repaired the 1.8.x semver range, we could also do that 3.0.0 as 2.0.0. If we do it as 3.0.0 with 1.8.4 re-released as 2.0.0, I'm not sure who would end up using 2.x?

Right now we're on 1.8.x which we briefly broke and now fixed. The next seems 2.0, I think :)

Do you want to go ahead with 3.0 after this?

**Comment by jdforrester** [comment]
> I see. That could work, yeah. But given this 2.0.0 is the same as 1.8.4 and we've already repaired the 1.8.x semver range, we could also do that 3.0.0 as 2.0.0. If we do it as 3.0.0 with 1.8.4 re-released as 2.0.0, I'm not sure who would end up using 2.x?
>
> Right now we're on 1.8.x which we briefly broke and now fixed. The next seems 2.0, I think :) 

1.8.4 doesn't exist (and neither does 1.8.3 for that matter). We haven't repaired anything. This patch is me trying to repair things.

The users of 2.0.0 are the people who complained. See the discussion on #17 and #24.

> Do you want to go ahead with 3.0 after this?

Sure. Wikimedia will switch straight to 3.0.

**Comment by Krinkle** [comment]
I see. It was prep, but we didn't do that release. Okay.

**Pull request merged**
